# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170706_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='teacher/default.jpg', upload_to='teacher/%Y/%m/', verbose_name='\u5c01\u9762'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u673a\u6784\u540d\u79f0'),
        ),
    ]
