# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170706_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='click_mum',
            new_name='click_num',
        ),
        migrations.RenameField(
            model_name='courseorg',
            old_name='fav_mun',
            new_name='fav_num',
        ),
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('gr', '\u4e2a\u4eba'), ('gx', '\u9ad8\u6821'), ('pxjg', '\u57f9\u8bad\u673a\u6784')], default='pxjg', max_length=4),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='student_num',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570'),
        ),
    ]
