# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-25 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='desc',
            field=models.CharField(default='\u6682\u65e0\u63cf\u8ff0', max_length=300, verbose_name='\u63cf\u8ff0'),
        ),
    ]
