# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='\u65f6\u957f\uff08\u5206\u949f\uff09'),
        ),
    ]
