# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_video_learn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teach_you',
            field=models.CharField(default='', max_length=300, verbose_name='\u5b66\u5230\u77e5\u8bc6'),
        ),
        migrations.AddField(
            model_name='course',
            name='you_need_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u524d\u51c6\u5907'),
        ),
    ]
