# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-20 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20170719_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path2',
            field=models.CharField(default='', max_length=200, verbose_name='OGG\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(default='', max_length=200, verbose_name='MP4\u8def\u5f84'),
        ),
    ]
